case1_labels = ['A';'B'];
case2_labels = ['C';'D';'E'];

figure
confusionchart(C1_MED, case1_labels, 'Title', 'Case 1 MED', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C1_GED, case1_labels, 'Title', 'Case 1 GED', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C1_MAP, case1_labels, 'Title', 'Case 1 MAP', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C1_NN, case1_labels, 'Title', 'Case 1 NN', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C1_5NN, case1_labels, 'Title', 'Case 1 5NN', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C2_MED, case2_labels, 'Title', 'Case 2 MED', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C2_GED, case2_labels, 'Title', 'Case 2 GED', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C2_MAP, case2_labels, 'Title', 'Case 2 MAP', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C2_NN, case2_labels, 'Title', 'Case 2 NN', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');

figure
confusionchart(C2_5NN, case2_labels, 'Title', 'Case 2 5NN', ...
                                     'RowSummary', 'absolute', ...
                                     'ColumnSummary', 'absolute');
